In [1]:
import numpy as np

# Example sentence tokens = 4 words
# Each word embedding dimension = 4 (simplified)
X = np.array([
    [1, 0, 1, 0],   # What
    [0, 1, 0, 1],   # are
    [1, 1, 1, 0],   # symptoms
    [0, 0, 1, 1]    # diabetes
])

# Weight matrices (random for example)
W_Q = np.random.rand(4, 4)
W_K = np.random.rand(4, 4)
W_V = np.random.rand(4, 4)

# Step 1: Compute Q, K, V
Q = X @ W_Q
K = X @ W_K
V = X @ W_V

# Step 2: Compute Attention Scores
# Q × K^T
scores = Q @ K.T

# Step 3: Scaling
d_k = K.shape[1]
scaled_scores = scores / np.sqrt(d_k)

# Step 4: Softmax
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

attention_weights = softmax(scaled_scores)

# Step 5: Final Output
output = attention_weights @ V

print("Attention Scores:\n", scores)
print("\nScaled Scores:\n", scaled_scores)
print("\nAttention Weights:\n", attention_weights)
print("\nFinal Output:\n", output)

Attention Scores:
 [[2.01666309 2.43923726 3.17990875 2.44235981]
 [2.97814002 3.5836348  4.86560242 3.3404385 ]
 [3.97620087 4.64300855 6.2359948  4.63091963]
 [2.13592793 2.15985552 3.25464027 2.14891455]]

Scaled Scores:
 [[1.00833155 1.21961863 1.58995438 1.2211799 ]
 [1.48907001 1.7918174  2.43280121 1.67021925]
 [1.98810044 2.32150427 3.1179974  2.31545981]
 [1.06796397 1.07992776 1.62732013 1.07445727]]

Attention Weights:
 [[0.19006337 0.23477899 0.34001181 0.23514583]
 [0.16335285 0.22110992 0.41974348 0.19579375]
 [0.14538374 0.20291366 0.45001175 0.20169085]
 [0.20972733 0.21225153 0.36692755 0.21109358]]

Final Output:
 [[1.5129405  0.98461713 0.99830218 1.43606096]
 [1.53536116 1.02572829 1.07453991 1.49917677]
 [1.54771685 1.03738777 1.09548888 1.52150302]
 [1.49376909 0.99054581 1.03308412 1.44827324]]
